#   _____ __  __ _____     _____                 _        _               __  __           _
#  / ____|  \/  |  __ \   / ____|               | |      | |             |  \/  |         | |
# | (___ | \  / | |__) | | (___  _ __   ___  ___| |_ __ _| |_ ___  _ __  | \  / | ___   __| | ___
#  \___ \| |\/| |  ___/   \___ \| '_ \ / _ \/ __| __/ _` | __/ _ \| '__| | |\/| |/ _ \ / _` |/ _ \
#  ____) | |  | | |       ____) | |_) |  __/ (__| || (_| | || (_) | |    | |  | | (_) | (_| |  __/
# |_____/|_|  |_|_|      |_____/| .__/ \___|\___|\__\__,_|\__\___/|_|    |_|  |_|\___/ \__,_|\___|
#                               | |
#                               |_|

#If the command /s is enabled (/s enable overrules this)
enabled: true

#If a player receives the night vision effect while in spectator mode
night-vision: true

#the max speed a player is allowed to go (Minimum 1)
max-speed: 5

#If when a player logs on in spectator mode they will be teleported back
teleport-back: false



#Message when gamemode set to spectator mode
spectator-mode-message: '&9Setting gamemode to &b&lSPECTATOR MODE'

#Message when gamemode set to survival mode
survival-mode-message: '&9Setting gamemode to &b&lSURVIVAL MODE'

#Message when user preforms the command while falling (error message)
falling-message: '&cHey you &lcan not &r&cdo that while falling!'

#Message when user preforms command in world it is not allowed in
world-message: '&cHey you&l can not &r&cdo that in that world!'

#Message when user does not have permission to execute the command
permission-message: '&cYou do not have permission to do that!'

#Message when spectator mode is disabled and the user runs the command
disabled-message: '&cSpectator Mode is &lnot &r&cenabled by the server!'

#Message when a non-player runs the command with no arguments
console-message: '&cYou are &lnot &ca player!'

#Message when spectator mode has been disabled
disable-message: '&dSpectator mode has been &ldisabled'

#Message when spectator mode has been enabled
enable-message: '&dSpectator mode has been &lenabled'

#Message when the config.yml is reloaded
reload-message: '&bThe config file has been reloaded!'


#Whether to enforce the worlds
enforce-worlds: false
#The names of the worlds spectator mode is allowed in
worlds-allowed: [world, world_nether, world_the_end]

#If the y level is limited to the number in y-level in spectator mode
enforce-y: false

#see above (players can not go below this level)
y-level: 0

#If a player is not allowed to go through non-see-throughable blocks in spectator mode
disallow-non-transparent-blocks: false

#If a player is not allowed to go through blocks in spectator mode
disallow-all-blocks: false

#Whether to make it so players can not go past a certain distance in spectator mode. The permission spectator-bypass bypasses this
enforce-distance: false

#See above (blocks)
distance: 64