name: SpectatorMode
version: 1.3.11
main: me.ohowe12.spectatormode.SpectatorMode
api-version: 1.13

commands:
  s:
    description: This command will set your gamemode to spectator or survival.
  speed:
    description: Changes the flying speed in spectator mode of the player.
  seffect:
    description: This command will toggle the effects of night vision and conduit while in spectator mode

permissions:
  spectator-use:
    default: true
  spectator-enable:
    default: op
  speed-use:
    default: true
  spectator-bypass:
    default: op
  spectator-force:
    default: op
  spectator-toggle:
    default: true
